name: 1.0$(Rev:.r)

# simplified trigger (implied branch)
trigger:

- main

variables:
  name: John

pool:
  vmImage: ubuntu-latest

jobs:

- job: job1
  steps:
    - checkout: self
    - script: echo "Hello, $(name)

- job: job2
  steps:
    - script: echo "job2"
  dependsOn: job3

- job: job3
  steps:
    - script: echo "job3"
  dependsOn: job1
